# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.5"

services:
  namenode: #Master (metadata/chunk)
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      hadoop_network:
        ipv4_address: 172.200.0.2

  datanode1: #Slave1
    image: bde2020/hadoop-datanode:latest
    container_name: datanode1
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      hadoop_network:
        ipv4_address: 172.200.0.3

  webapi:
    image: webapi
    build:
      context: src/WebApi
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  sentinelscraper:
    image: sentinel-scraper
    build:
      context: src/SentinelScraper
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      hadoop_network:
        ipv4_address: 172.200.0.240

networks:
  hadoop_network:
    name: hadoop
    ipam:
      config:
        - subnet: 172.200.0.0/24

volumes:
  hadoop_namenode:
    name: namenode
  hadoop_datanode1:
    name: datanode1
  