services:
  scraper-dk:
    image: nikolaidamm/sentinel-ndwi-scraper:latest
    container_name: scraper-dk
    command: --countrycode dk --days 1095
    volumes:
      - scraper_data:/processed/DK
    networks:
      cscourse:

networks:
  cscourse:
    name: hadoop
    ipam:
      config:
        - subnet: 172.202.0.0/24

volumes:
  scraper_data: