services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      cscourse:
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PARTITION_ASSIGNMENT_STRATEGY: org.apache.kafka.clients.consumer.RoundRobinAssignor
    volumes:
      - confluent_kafka:/var/lib/kafka/data
    depends_on:
      - "zookeeper"
    networks:
      cscourse:

volumes:
  confluent_kafka:
    name: kafka

networks:
  cscourse:
    name: hadoop
    ipam:
      config:
        - subnet: 172.202.0.0/24