name: Build and test webapi

on:
  push:
    paths:
      - "src/WebApi/**"
      - ".github/workflows/build-and-test-webapi.yml"
  pull_request:
    paths:
      - "src/WebApi/**"
      - ".github/workflows/build-and-test-webapi.yml"
env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Build
        run: dotnet build ./src/WebApi/WebApi.csproj --configuration Release
        
      - name: Publish codecoverage to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info