name: Build LaTeX report

on:
  push:
    paths:
      - "report/**"
      - ".github/workflows/build-latex.yml"
  pull_request:
    paths:
      - "report/**"
      - ".github/workflows/build-latex.yml"

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - uses: xu-cheng/latex-action@v2
      with:
        working_directory: report/
        root_file: main.tex
        args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
    - name: Upload pdf to GitHub Workflow
      uses: actions/upload-artifact@v2.3.0
      with:
        name: report
        path: report/main.pdf