name: Build LaTeX report

on: [push, pull_request]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: report/main.tex