name: Publish SentinelNDWIScraper to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - "src/SentinelNDWIScraper/**"
      - ".github/workflows/publish-scraper-to-dockerhub.yml"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NIKOLAI_DOCKER_USERNAME }}
          password: ${{ secrets.NIKOLAI_DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src/SentinelNDWIScraper/
          push: true
          tags: nikolaidamm/sentinel-ndwi-scraper:latest