name: Publish SentinelNDWIScraper to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - "src/SentinelNDWIScraper/**"
      - ".github/workflows/publish-scraper-to-dockerhub.yml"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NIKOLAI_DOCKER_USERNAME }}
          password: ${{ secrets.NIKOLAI_DOCKER_PASSWORD }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/SentinelNDWIScraper/
          push: true
          tags: latest